1.In a population of interest, a sample of 9 men yielded a sample average brain volume of 1,100cc and a standard deviation of 30cc. What is a 95% Student's T confidence interval for the mean brain volume in this new population?
```{r}
#1
#n=9
#mn=1100
#s=30
#These +- signes are same as
# 1100 + c(-1,1)*qt(.95,9-1)*30/sqrt(9)
1100 + c(-1,1) * qt(0.975, 8) * 30/sqrt(9)
```

q2-see homework 2 and Gosset's t distr slide. You don't know the s instead of mn now. Remember:
mn + qt(0.975,n-1) * s / sqrt(n)
```{r}
#n=9
#mn=-2
#s?
#-2 + qt(.975, df = 8) * s / sqrt(9)
#what is s?
2*sqrt(9)/qt(.975, df = 8) # is = s
```

q4.
```{r}
#old system
#n:10
#mean:5
#variance:0.68
#square root of the Variance is sd
# sd: sqrt(0.68)

#new system
#n:10
#mean:3
#variance:0.6
#square root of the Variance is sd
# sd: sqrt(0.6)

# Do
#new - #old
#constant variance: var.equal=T

# See sbp example of t test video around 18.19
# Total n is 20
sp <- sqrt((9*0.68 + 9 * 0.6)/(20-2))
3-5 + c(-1,1) * qt(0.975,10+10) * sp * sqrt(1/10 + 1/10)

```

q6
```{r}
#old: mean 6 / sd 2
#new: mean 4 / sd 0.5
sp <- sqrt((199*0.5 + 199 * 2)/(200-2))
6-4 + c(-1,1) * qt(0.975,100+100) * sp * sqrt(1/100 + 1/100) 
```


q7
```{r}
n1 <- n2 <- 9
x1 <- 3  ##treated
x2 <- 1  ##placebo
s1 <- 1.5  ##treated
s2 <- 1.8  ##placebo
#sp<-sqrt( (n1-1)*s1 + (n2-1)*s2)/(n1+n2-2)
sp2<-sqrt((n1-1)*s1^2+(n2-1)*s2^2)/(n1+n2-2)
#x1-x2 + c(-1,1) * qt(0.95,n1+n2) * sp2 * sqrt(s1^2/n1 + s2^2/n2) 
x1-x2 + c(-1,1) * qt(0.95,n1+n2) * sp2 * sqrt(1/n1 + 1/n2) 

```

```{r}
n1 <- 9; n2 <- 9
sp <- sqrt(((n1-1) * 1.5^2 + (n2-1) * 1.8^2) / (n1 + n2-2))
md <- -3 - 1
semd <- sp * sqrt(1/n1 + 1/n2)
md + c(-1, 1) * qt(.95, n1 + n2 - 2) * semd
```